# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Pre Build started on `date`
      - npm install
      - echo NPM isntall completed!!
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo copy contents
      - aws s3 sync s3://s3-github-cp/build s3://s3-github-cp
# Include only the files required for your application to run.
artifacts:
  files:
     - build/**/*
     - package.json
